import streamlit as st
from ui.theme import inject_css
from ui.components import card, render_score_gauge, small_kv
from core.model_logic import load_model_and_features, predict_for_user
from core.data_processing import compute_emi_affordability, compute_credit_flags
from core.llm_local import generate_local_explanation
import json



def render_page():
    st.header("LoanScore+")
    st.markdown("Upload a JSON and view results below.")

def render_profile_card(user_profile):
    def body():
        st.write(f"**{user_profile.get('name')}**")
        st.write(user_profile.get('upi_id'))
        small_kv('Mobile', user_profile.get('mobile'))
        small_kv('Account', user_profile.get('account_no'))
    card('User Profile', body)

def render_page():
    inject_css()
    st.markdown("<div class='header-row'><h1>LoanScore+</h1><div class='small-muted'>Professional demo</div></div>", unsafe_allow_html=True)
    uploaded = st.file_uploader('Upload user JSON', type=['json'])
    if not uploaded:
        st.info('Upload a user JSON file.')
        return
    user = json.load(uploaded)

    model, features = load_model_and_features()
    preds = predict_for_user(model, features, user)
    score = preds['score']
    feats = preds['features']

    col1, col2 = st.columns([1,2])
    with col1:
        st.markdown("<div class='card score-card'>", unsafe_allow_html=True)
        render_score_gauge(score)
        st.markdown("<div style='padding-left:8px'><div class='small-muted'>Eligibility Score</div></div>", unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)
    with col2:
        def stats():
            small_kv('Income', user.get('user_profile',{}).get('income_monthly'))
            small_kv('EMI Load', compute_emi_affordability(user, feats)['current_emi_load'])
            small_kv('Repayment Rate', feats.get('repayment_rate_12m'))
        card('Financial Summary', stats)

    col3, col4 = st.columns([1,2])
    with col3:
        render_profile_card(user.get('user_profile', {}))
        flags = compute_credit_flags(feats)
        def fb():
            for t,msg,c in flags:
                st.write(f"- **{t}**: {msg}")
        card('Credit Flags', fb)
    with col4:
        def ai():
            explanation = generate_local_explanation(user, score, feats)
            st.markdown('### AI Explanation')
            st.write(explanation)
        card('Personalized Advice', ai)

    st.markdown('---')
    st.markdown('<div class="small-muted">Generated by LoanScore+</div>', unsafe_allow_html=True)
